ProyectoRespaldo -plantilla/ProyectoRespaldo/Controllers/MVirtualController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoRespaldo.Controllers
{
    public class MVirtualController : Controller
    {
        // GET: MVirtual
        public ActionResult Index_MVirtual()
        {
            return View();
        }

        // GET: MVirtual/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MVirtual/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MVirtual/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MVirtual/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MVirtual/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MVirtual/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MVirtual/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProyectoRespaldo -plantilla/ProyectoRespaldo/Controllers/PoliticaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoRespaldo.Controllers
{
    public class PoliticaController : Controller
    {
        // GET: Politica
        public ActionResult Index_Politica()
        {
            return View();
        }

        // GET: Politica/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Politica/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Politica/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Politica/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Politica/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Politica/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Politica/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProyectoRespaldo -plantilla/ProyectoRespaldo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mis aplicaciones ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema de Respaldo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicios", "Index", "Home")</li>
                    @Html.Partial("_LoginPartial2")

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoRespaldo -plantilla/ProyectoRespaldo/Views/Shared/_LoginPartial2.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maquinas Virtuales <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Maquinas Virtuales", "Index_MVirtual", "MVirtual")</li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Politicas <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Politicas", "Index_Politica", "Politica")</li>
                </ul>
            </li>
        </ul>
    }
}